### ISSUE TITLE
Avoid making groups with 3 totally different timezones

### ISSUE THREAD

**Issue by squelart** [mozilla/perf-triage#2]
E.g., this week we have Toronto (UTC-4), Finland (+3), Australia (+10), making it pretty much impossible to meet all together.

To avoid the difficulty of handling real timezones, I think we could divide people in broad areas, like Americas 🌎, Europe/Africa 🌍, and Australasia 🌏, and prevent groups covering more than two areas.

**Comment by davehunt** [comment]
Great idea @squelart! Would you be willing to work on a patch to add this to the script?

**Comment by davehunt** [comment]
This should be fixed by https://github.com/mozilla/perf-triage/commit/c3039581b21f030c3bf476573c08d5af89978b8a
