### ISSUE TITLE
I think "leads" should only be people with existing experience in triaging perf bugs

### ISSUE THREAD

**Issue by squelart** [mozilla/perf-triage#3]
I've been marked as "lead" (probably because of my job title?), but not being in the main perf team I've never triaged perf bugs, so I'm not certain exactly how to deal with them; hopefully my teammates will know, though the separate timezones don't help this week. Also the triage guidelines are not ready yet.
I think we should reserve this label to people who have participated in perf triage at least once or twice.

**Comment by davehunt** [comment]
This is based on level, so all senior engineers in the perf team are considered leads. We could perhaps make this opt-in (or opt-out?) via pull requests. It would certainly be less of an issue if we had the triage guidelines in place.

**Comment by davehunt** [comment]
We now have triage guidelines, and a more consistent and repeatable process for triaging. All senior engineers should be comfortable as lead sheriffs, but they are not automatically enrolled, so this will only happen when agreed.
