### ISSUE TITLE
Automatically regenerate the rotation list when a change is made

### ISSUE THREAD

**Issue by pslawless** [mozilla/perf-triage#4]
ex: When the team list is updated (someone leaves the team, goes on vacation or leave, etc).

**Comment by davehunt** [comment]
The rotation is generated each week for this/next week. We might improve this further by making the script aware of the current week and run more frequently to respond to changes in a smaller timeframe. For now, as we're only looking one week ahead, I think we can depend on the nominated sheriffs to manage any short term changes to availability.
